name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the application
      - name: Install and Test
        run: |
          npm install
          npm run test
